resonatehq/resonate-sdk-ts

- .eslintrc.yml
- .github/workflows/cicd.yaml
- .gitignore
- jest.config.js
- lib/core/bucket.ts
- lib/core/error.ts
- lib/core/logger.ts
- lib/core/loggers/opentelemetry.ts
- lib/core/loggers/test.ts
- lib/core/retries/exponential.ts
- lib/core/retries/linear.ts
- lib/core/stores/local.ts
- lib/core/stores/remote.ts
- lib/resonate.ts
- test/retry.test.ts
- test/store.test.ts
```ts
run<A extends any[], R>(func: DurableFunction<A, R> | string, ...args: WithOpts<A>): Promise<R>;
```
Extends `context.run()` to optionally accept a string, if a string is provided Resonate will start an instance of `RInvocation` which create and polls a promise until it is complete. The promise is expected to be resolved/reject out-of-process.
> Add remote invocation

- lib/core/lock.ts
- lib/core/storage.ts
- lib/core/storages/indexdb.ts
- lib/core/storages/memory.ts
- lib/core/storages/withTimeout.ts
- lib/core/store.ts
- lib/core/stores/local.ts
- lib/core/stores/remote.ts
- lib/resonate.ts
- test/lock.test.ts
- test/scheduler.test.ts
```ts
export interface IStore {
readonly promises: IPromiseStore;
readonly schedules: IScheduleStore;
readonly locks: ILockStore;
}
export interface IStorage<T> {
rmw<X extends T | undefined>(id: string, func: (item: T | undefined) => X): Promise<X>;
rmd(id: string, func: (item: T) => boolean): Promise<void>;
all(): AsyncGenerator<T[], void>;
}
```
The local store components can be implemented as
```ts
IStorage<DurablePromise>
IStorage<Schedule>
IStorage<Lock>
```
And the actual implementation ca be implemented using these storage primitives, consolidating the business logic in the `LocalStore`.
> Refactor Stores and Storages and implement local locking

- lib/resonate.ts
```ts
const resonate = new Resonate();
resonate.schedules.create(...);
resonate.schedules.get(...);
resonate.schedules.delete(...);
```
> Add get accessor for default schedule store

- lib/core/store.ts
- lib/core/stores/remote.ts
1. fix locks tryAcquire
2. fix schedules create
> Locks and Schedules Create API fix

- README.md
- lib/core/lock.ts
- lib/core/opts.ts
- lib/core/store.ts
- lib/core/stores/local.ts
- lib/core/stores/remote.ts
- lib/resonate.ts
```ts
schedule<A extends any[], R>(name: string, cron: string, func: DurableFunction<A, R>, ...args: A): Promise<R>;
```
- promiseTimeout is relative so we have to add it to Date.now for local store
- we need to add the same tags to scheduled promises that we add on the server (resonate:schedule and resonate:invocation)
- the template variables are `{{.id}}` and `{{.timestamp}}`
- move processId to the RemoteLockStore constructor so that the store and processId have a 1-1 relationship, that way we only have to hold on to one interval callback per store
- the response type of the heartbeat api is `{locksAffected: number}` instead of just boolean
> Add schedule function to resonate

- test/lock.test.ts
add explicit checks in throw error message
> Explicit checks in tests to ensure that error messages are consistent

- lib/async.ts
- lib/core/encoders/json.ts
- lib/core/errors.ts
- lib/core/execution.ts
- lib/core/future.ts
- lib/core/invocation.ts
- lib/core/promises/promises.ts
- lib/core/stores/local.ts
- lib/core/stores/remote.ts
- lib/generator.ts
- test/async.test.ts
- test/generator.test.ts
DurablePromises returns the appropriate resonate error and this error bubbles up to the future.
> Consolidate errors

- lib/async.ts
- lib/core/execution.ts
- lib/core/future.ts
- lib/core/invocation.ts
- lib/core/options.ts
- lib/core/promises/promises.ts
- lib/core/store.ts
- lib/core/stores/local.ts
- lib/core/stores/remote.ts
- lib/generator.ts
- lib/resonate.ts
- test/async.test.ts
- test/durable.test.ts
- test/generator.test.ts
- test/options.test.ts
- test/versions.test.ts
| option | default | behaviour |
| --- | --- | --- |
| durable | true | represent the execution as a durable promise |
| lock | true | acquire a lock before invoking a function |
| eid | `utils.randomId` | a unique execution id, can be a function or a string, used when acquiring a lock |
| idempotencyKey | `utils.hash` | can be a function or a string, defaults to a simple hash function |
> Add durable and lock options

- lib/core/execution.ts
- lib/core/future.ts
- lib/core/promises/promises.ts
ResonatePromise extends a javascript promise and exposes created to signal when the durable promise has been created on the server. This fix ensures fork does not prematurely await, which caused the created promise to unnecessarily be delayed until the promise was completed.
> Fix created promise on ResonatePromise

- lib/async.ts
- lib/core/execution.ts
- lib/core/invocation.ts
- lib/core/promises/promises.ts
- lib/generator.ts
- package-lock.json
This time indicates the time that the durable promise was created, if an execution has opted out of a durable promise the time that the invocation was created will be used instead.
> Add createdOn time to context

- lib/core/execution.ts
- lib/core/promises/promises.ts
Sync and wait can be used to join on the completion of a durable promise. Sync resolves when the durable promise completed, wait resolves to the value (or throws a corresponding error) when the durable promise is completed.
> Add sync and wait to durable promise class

- lib/core/promises/promises.ts
If this timeout is not cleared, a program will not halt until the timeout elapses even in the case where the durable promise completes.
> Clear timeout in sync

- lib/async.ts
- lib/core/encoders/json.ts
- lib/core/invocation.ts
- lib/core/retry.ts
- lib/resonate.ts
- test/resonate.test.ts
With this change we start storing the retry policy with the DurablePromise.
This enables the recovery path to use the retry policy that was set when executing the function originally instead of the default retry policy.
> Store the retry policy with the DurablePromise.

- lib/async.ts
- lib/core/execution.ts
- lib/core/invocation.ts
- lib/core/options.ts
- lib/core/promises/promises.ts
- lib/core/utils.ts
- lib/generator.ts
- lib/resonate.ts
- test/options.test.ts
Default options in the invocation were in reality
the registered options from the top level function call. This commit changes the code to express that more clearly and removes the split functions that were a source of confusion.
> Removes "default" options from the invocation

- lib/core/promises/promises.ts
- lib/core/promises/types.ts
- lib/core/storages/memory.ts
- lib/core/storages/withTimeout.ts
- lib/core/store.ts
- lib/core/stores/local.ts
- lib/core/stores/remote.ts
Implements the proposed change in
https://github.com/resonatehq/resonate-sdk-ts/issues/126
> Replace DurablePromise union type with single type

- lib/async.ts
- lib/core/calls.ts
- lib/core/utils.ts
- lib/resonate.ts
- test/async.test.ts
- test/options.test.ts
- test/utils.test.ts
This PR implements the first part of this proposal #120. It focuses mostly in bringing the FC concepts to the api surface, future PR will bring this concept deeper into the architecture.
> Add initial support for Function Call types

- lib/resonate.ts
As part of the resonate invoke refactor, this two functions were missing
> Reintroduce `resonate.options` and `ctx.options` functions

- lib/resonate.ts
- test/options.test.ts
This should improve the default experience during recovery,
and allows more advance use cases to use locks when necessary.
> Make locks for the top level function opt-in

- lib/core/promises/types.ts
- lib/resonate.ts
- test/options.test.ts
- test/userResources.test.ts
We had some code repetition around handling a completed durable promise. The repetition was fine, how ever this pattern will come to callbacks and tasks and we will have it in atleast 4 more places, having to write that code that many times is error prone and verbose.
This change also fixes a bug made evident by this helper funciton where we were returning the value computed by the function directly instead of the value stored in the completed durable promise.
> Add handleCompletePromise helper function

- src/computation.ts
- src/context.ts
- src/coroutine.ts
- src/decorator.ts
- src/handler.ts
- src/network/remote.ts
- src/registry.ts
- src/resonate-inner.ts
- src/resonate.ts
- src/types.ts
- src/util.ts
- tests/coroutine.test.ts
- tests/decorator.test.ts
```ts
// run
public async run<F extends Func>(id: string, func: F, ...args: Params<F>): Promise<Return<F>>;
public async run<T>(id: string, name: string, ...args: any[]): Promise<T>;
// rpc
public async rpc<F extends Func>(id: string, func: F, ...args: Params<F>): Promise<Return<F>>;
public async rpc<T>(id: string, name: string, ...args: any[]): Promise<T>;
// beginRun
public async beginRun<F extends Func>(id: string, func: F, ...args: Params<F>): Promise<Handle<Return<F>>>;
public async beginRun<T>(id: string, func: string, ...args: any[]): Promise<Handle<T>>;
// beginRpc
public async beginRpc<F extends Func>(id: string, func: F, ...args: Params<F>): Promise<Handle<Return<F>>>;
public async beginRpc<T>(id: string, func: string, ...args: any[]): Promise<Handle<T>>;
```
> Implement resonate run, rpc, beginRun, beginRpc

- tests/dst.test.ts
Skipping the dst unit tests, at the moment they always fail and generate output that hide the result of the other tests, we  can undo this change after  merge to main and solve the main concurrency issues.
> skip dst tests

- dev/network.ts
- dev/server.ts
- sim/main.ts
- sim/src/server.ts
- sim/src/worker.ts
- src/computation.ts
- src/coroutine.ts
- src/handler.ts
- src/network/network.ts
- src/network/remote.ts
- src/nursery.ts
- src/resonate-inner.ts
- src/types.ts
- tests/computation.test.ts
- tests/coroutine.test.ts
- tests/nursery.test.ts
The nursery formalizes the control flow logic of the computation and separates it (as much as possible from the business logic. All code paths inside result in a call to either:
- `nursery.cont`: the nursery is not done, but is no longer actively executing
- `nursery.done`: the nursery is done, the provided callback will be called
Additionally this PR makes the following changes:
- simplifies type naming for core types (Request, Response, Message)
- adds type annotation to network `recv` function
- moves optional `onMessage` property to a subscription model
- replace `CompResult` with simplified `Status` (no longer expresses platform errors)
- propagate platform errors up callback chain (only a boolean is returned, TODO: errors will be logged at error site)
> Add nursery

- dev/network.ts
- dev/server.ts
- sim/src/worker.ts
- src/computation.ts
- src/handler.ts
- src/heartbeat.ts
- src/network/network.ts
- src/network/remote.ts
- src/promises.ts
- src/resonate-inner.ts
- src/resonate.ts
- src/schedules.ts
- src/tasks.ts
- tests/computation.test.ts
- tests/coroutine.test.ts
- tests/store.promises.test.ts
- tests/store.schedules.test.ts
- tests/store.tasks.test.ts
```ts
export type ResponseFor<T extends Request> = Extract<Response, { kind: T["kind"] }>;
```
This utility type annotation lets us move the type casting behind the interface so that we only have to do it once in the callee rather than on the caller side. 
Example usage (in remote network implementation):
```ts
send<T extends Request>(req: T, callback: (timeout: boolean, response?: ResponseFor<T>) => void): void {
this.handleRequest(req).then(
(res) => {
util.assert(res.kind === req.kind, "res kind must match req kind");
callback(false, res as ResponseFor<T>);
},
() => {
// TODO: log error here
callback(true);
},
);
}
```
> Use ReponseFor in network interface

- .github/workflows/dst.yml
- package-lock.json
- package.json
DST has been failing, running the command with tsx rather than ts-node seems to do the trick, though I'm not sure why. Nevertheless, since we already use npx for type checking aligning these two should mean that the type checker will find potential future issues upfront.
> Fix npm run dst
