resonatehq/resonate-sdk-ts

lib/core/storage.ts, lib/core/storages/indexdb.ts, lib/core/storages/memory.ts, lib/core/store.ts, lib/core/stores/local.ts, lib/core/stores/remote.ts, lib/resonate.ts, test/retry.test.ts
The recorvery/schedule path works like this:
1. search for all matching pending promises
2. decode the params, the params dictate which function to call with which parameters
3. call the function with the provided parameters (the lock ensure mutual exclusion)
=> Add recovery path

package.json, test/browser.test.ts
adding browser test 
- local
- durable
=> adding browser test

lib/core/stores/local.ts, test/store.test.ts
=> Add store tests for timedout promises

lib/resonate.ts
=> Add manual create, resolve, and reject functions to resonate class

lib/core/stores/remote.ts, test/lock.test.ts
=> Fix Lock tests

lib/resonate.ts
Promise polls for a remote durable promise and resolve/rejects with the value.
=> Add promise on context

jest.config.js, lib/core/stores/remote.ts, package.json, tsconfig.json
- esnext configurations
- remove unused dependencies
- all tests pass
=> updating to esm and fix dependencies

lib/core/error.ts, lib/core/storages/indexdb.ts, lib/core/stores/local.ts, lib/core/stores/remote.ts
- adding resonate cancelled and timedout error
- adding killed error
=> Resonate Cancelled and Timedout Error

lib/core/error.ts
adding full stop in error messages
=> fix main build - test 

.github/workflows/release.yaml, RELEASE.md, package.json
bump version and release notes
=> RELEASE 0.3.2

lib/async.ts, lib/core/invocation.ts, lib/core/options.ts, lib/core/stores/local.ts, lib/generator.ts, lib/resonate.ts, test/resonate.test.ts, test/versions.test.ts
Additionally add resonate tests that test the various overloaded signatures of the following functions:
- register
- registerModule
- run
- schedule
=> Move register and run version to options

lib/core/stores/remote.ts
Fixes https://github.com/resonatehq/resonate/issues/217
Depends On: 
- https://github.com/resonatehq/resonate/pull/263
=> feat(ms): update to have correct field name

lib/async.ts, lib/core/execution.ts, lib/core/options.ts, lib/generator.ts, lib/resonate.ts, test/combinators.test.ts
=> Add promise combinators and convenience functions

lib/async.ts, lib/core/promises/promises.ts, lib/core/storages/withTimeout.ts, test/sleep.test.ts
Sleeps for the specified amount of time. The amount of time is durable once the Durable Promise is created and will not be affected by application restarts.
=> Add context sleep

lib/async.ts, lib/core/calls.ts, lib/core/execution.ts, lib/core/invocation.ts, lib/core/options.ts, lib/resonate.ts, test/async.test.ts, test/combinators.test.ts, test/options.test.ts
lock -> shouldLock
poll -> pollFrequency
retry -> retryPolicy
=> Rename some options to improve clarity and intent of them

src/computation.ts, src/handler.ts, tests/computation.test.ts
To be able to handle our Network abstraction and
DST it is necessary that our code is written in
callback passing style.
=> convert to callback style

src/handler.ts, src/resonate-inner.ts, src/resonate.ts
Subscribe to receive an event and resolve the corresponding promise in beginRun.
=> Subscribe on beginRun

src/computation.ts, src/context.ts, src/network/network.ts, src/network/remote.ts, src/resonate-inner.ts, src/resonate.ts, src/types.ts, tests/computation.test.ts, tests/resonate.test.ts, tsconfig.json
When we have a task, drop it. If there is a local handle then subscribe to the promise, otherwise ignore.
=> Handle platform level errors

src/computation.ts, src/context.ts, src/core.ts, src/coroutine.ts, src/decorator.ts, src/index.ts, src/resonate-inner.ts, src/resonate.ts, src/types.ts, src/util.ts, tests/computation.test.ts, tests/decorator.test.ts
=> Add core and rearrange types

dev/server.ts
Otherwise this creates chaos when a task needs to be dropped
=> Wait 5s before sending message again on drop task
